# global vars to make devtools happy!
globalVariables(
  c(".",
    "Company",
    "tickers",
    "Code",
    "Ticker (in Yahoo Finance)",
    "Ticker (on TSX)",
    "symbol",
    "adjusted",
    "download",
    "error",
    "high",
    "index",
    "low",
    "part1",
    "part2",
    "result",
    "volume",
    "Ticker symbol",
    "New Index Series Code",
    "Scrip Code (on BSE)",
    "Symbol",
    "Stock Code",
    "data",
    "samples",
    "splits",
    "fits",
    "id",
    "oos",
    "rmse",
    "out_of_sample",
    "mse",
    "mae",
    "mape",
    "mase"
  )

)
